import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CURA",
  description: "Generated by CSD Technologies",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "CURA",
  },
  icons: {
    icon: "/icon.ico",
    apple: [
      { url: "/apple-icon.png", sizes: "512x512", type: "image/png" },
    ],
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        {/* 🚀 الوسم المباشر المضمون لمتصفح Safari بحجم 512x512 ليطابق صورتك */}
        <link rel="apple-touch-icon" sizes="512x512" href="/apple-icon.png" />
        <meta name="apple-mobile-web-app-title" content="CURA" />
        <meta name="apple-mobile-web-app-capable" content="yes" />

        <Script
          id="theme-lang-sniffer"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const savedTheme = localStorage.getItem('clinic_theme') || 'midnight';
                document.documentElement.setAttribute('data-theme', savedTheme);
                
                const savedLang = localStorage.getItem('clinic_lang') || 'ar';
                document.documentElement.setAttribute('lang', savedLang);
                document.documentElement.setAttribute('dir', savedLang === 'ar' ? 'rtl' : 'ltr');
              })();
            `,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col relative">
        {/* المحتوى الأساسي للنظام (لوحة التحكم والصفحات) */}
        {children}
      </body>
    </html>
  );
}